# Generated by Django 2.0 on 2018-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='galleryURL',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
